import React, { useState, useEffect, useRef, useCallback } from 'react';
import { VisualizationEngine } from '../services/VisualizationEngine';
import TemplateLibraryManager from '../services/TemplateLibraryManager';
import ChartRenderer from './ChartRenderer';
import './VisualizationTab.css';

const VisualizationTab = ({
    apiResponse = null,
    nodes = [],
    onVisualizationUpdate = () => { },
    visualizationContext = null
}) => {
    const [visualizations, setVisualizations] = useState([]);
    const [activeVisualization, setActiveVisualization] = useState(null);
    const [customTemplate, setCustomTemplate] = useState('');
    const [selectedTemplate, setSelectedTemplate] = useState('');
    const [isTemplateEditorOpen, setIsTemplateEditorOpen] = useState(false);
    const [error, setError] = useState(null);
    const [previewData, setPreviewData] = useState(null);
    const [templateLibrary, setTemplateLibrary] = useState([]);
    const [suggestedCharts, setSuggestedCharts] = useState([]);
    const visualizationContainerRef = useRef(null);

    // Sample data for testing when no API response is available
    const sampleData = React.useMemo(() => ({
        users: [
            { name: 'John Doe', email: 'john@example.com', age: 30, status: 'active', score: 85 },
            { name: 'Jane Smith', email: 'jane@example.com', age: 25, status: 'active', score: 92 },
            { name: 'Bob Johnson', email: 'bob@example.com', age: 35, status: 'inactive', score: 78 },
            { name: 'Alice Brown', email: 'alice@example.com', age: 28, status: 'active', score: 95 },
            { name: 'Charlie Wilson', email: 'charlie@example.com', age: 42, status: 'pending', score: 88 }
        ],
        analytics: {
            pageViews: 15420,
            uniqueVisitors: 8750,
            bounceRate: 34.2,
            avgSessionDuration: 245,
            conversionRate: 3.8
        },
        performance: {
            responseTime: 245,
            errorRate: 1.2,
            uptime: 99.8,
            throughput: 1540
        },
        status: 200,
        responseTime: 245,
        size: 2048,
        timestamp: new Date().toISOString()
    }), []);

    const loadTemplateLibrary = useCallback(() => {
        const templates = TemplateLibraryManager.getAllTemplates();
        setTemplateLibrary(templates);
    }, []);

    const generateChartSuggestions = useCallback((data) => {
        const suggestions = VisualizationEngine.suggestChartTypes(data);
        setSuggestedCharts(suggestions);
    }, []);

    const generateDefaultVisualizations = useCallback((data) => {
        try {
            const newVisualizations = [];

            // Auto-generate visualizations using the enhanced engine
            const autoGenerated = VisualizationEngine.generateFromResponse(data, {
                maxRows: 50,
                title: 'API Response Data'
            });

            newVisualizations.push(...autoGenerated);

            // If data has users array, create additional visualizations
            if (data.users && Array.isArray(data.users)) {
                // Age distribution chart
                const ageData = data.users.map(user => ({
                    label: user.name,
                    value: user.age
                }));

                const ageChart = VisualizationEngine.generateChart('bar', ageData, {
                    title: 'User Age Distribution',
                    xLabel: 'Users',
                    yLabel: 'Age'
                });

                newVisualizations.push({
                    ...ageChart,
                    name: 'Age Distribution',
                    type: 'chart'
                });

                // Status pie chart if score exists
                if (data.users[0].score) {
                    const scoreData = data.users.map(user => ({
                        label: user.name,
                        value: user.score
                    }));

                    const scoreChart = VisualizationEngine.generateChart('line', scoreData, {
                        title: 'User Scores',
                        xLabel: 'Users',
                        yLabel: 'Score'
                    });

                    newVisualizations.push({
                        ...scoreChart,
                        name: 'User Scores Trend',
                        type: 'chart'
                    });
                }
            }

            // Analytics data visualization
            if (data.analytics) {
                const analyticsChart = VisualizationEngine.generateChart('doughnut', data.analytics, {
                    title: 'Analytics Overview'
                });

                newVisualizations.push({
                    ...analyticsChart,
                    name: 'Analytics Doughnut',
                    type: 'chart'
                });
            }

            // Performance metrics
            if (data.performance) {
                const performanceMetrics = VisualizationEngine.createMetrics(data.performance, {
                    title: 'Performance Metrics'
                });

                newVisualizations.push({
                    ...performanceMetrics,
                    name: 'Performance Dashboard',
                    type: 'metrics'
                });
            }

            setVisualizations(newVisualizations);
            onVisualizationUpdate(newVisualizations);

            // Set first visualization as active
            if (newVisualizations.length > 0) {
                setActiveVisualization(newVisualizations[0]);
            }

        } catch (err) {
            setError(`Failed to generate visualizations: ${err.message}`);
        }
    }, [onVisualizationUpdate]);

    // Handle visualization context (when response data is provided from endpoint testing)
    useEffect(() => {
        if (visualizationContext && visualizationContext.responseData) {
            const contextData = visualizationContext.responseData.data || visualizationContext.responseData;
            generateDefaultVisualizations(contextData);
            generateChartSuggestions(contextData);
            setPreviewData(contextData);
        }
    }, [visualizationContext, generateDefaultVisualizations, generateChartSuggestions]);

    useEffect(() => {
        // Use API response data if available, otherwise use sample data
        const dataToUse = apiResponse || sampleData;
        setPreviewData(dataToUse);

        // Load template library
        loadTemplateLibrary();

        // Auto-generate visualizations and suggestions
        generateDefaultVisualizations(dataToUse);
        generateChartSuggestions(dataToUse);
    }, [apiResponse, sampleData, loadTemplateLibrary, generateDefaultVisualizations, generateChartSuggestions]);

    const handleTemplateSelect = (templateId) => {
        setSelectedTemplate(templateId);
        const template = TemplateLibraryManager.getTemplate(templateId);
        if (template) {
            setCustomTemplate(template.template);
        }
    };

    const handleCustomVisualization = () => {
        try {
            if (!customTemplate.trim()) {
                setError('Please enter a template');
                return;
            }

            setError(null);
            const customViz = VisualizationEngine.set(customTemplate, previewData);

            const newVisualization = {
                ...customViz,
                name: 'Custom Visualization',
                type: 'custom'
            };

            setVisualizations(prev => [...prev, newVisualization]);
            setActiveVisualization(newVisualization);
            setIsTemplateEditorOpen(false);

            onVisualizationUpdate(newVisualization);
        } catch (err) {
            setError(`Template error: ${err.message}`);
        }
    };

    const handleDeleteVisualization = (vizId) => {
        setVisualizations(prev => prev.filter(viz => viz.id !== vizId));
        VisualizationEngine.remove(vizId);

        if (activeVisualization && activeVisualization.id === vizId) {
            const remaining = visualizations.filter(viz => viz.id !== vizId);
            setActiveVisualization(remaining.length > 0 ? remaining[0] : null);
        }
    };

    const renderVisualizationContent = (visualization) => {
        if (!visualization) return null;

        // If it's a chart visualization, render using ChartRenderer
        if (visualization.type === 'chart' && visualization.data && visualization.data.chartConfig) {
            const chartConfig = visualization.data.chartConfig;
            return (
                <div className="chart-visualization">
                    <ChartRenderer
                        type={chartConfig.type}
                        data={chartConfig.data}
                        options={chartConfig.options}
                        width={600}
                        height={400}
                    />
                </div>
            );
        }

        return (
            <div
                className="visualization-content"
                dangerouslySetInnerHTML={{ __html: visualization.rendered }}
            />
        );
    };

    return (
        <div className="visualization-tab">
            <div className="visualization-header">
                <div className="header-left">
                    <h3>Data Visualizations</h3>
                    <span className="visualization-count">
                        {visualizations.length} visualization{visualizations.length !== 1 ? 's' : ''}
                    </span>
                </div>
                <div className="header-actions">
                    <button
                        className="btn btn-secondary"
                        onClick={() => setIsTemplateEditorOpen(true)}
                    >
                        + Create Custom
                    </button>
                    <button
                        className="btn btn-secondary"
                        onClick={() => generateDefaultVisualizations(previewData)}
                    >
                        🔄 Refresh
                    </button>
                    {suggestedCharts.length > 0 && (
                        <div className="chart-suggestions">
                            <label>Suggested: </label>
                            {suggestedCharts.slice(0, 3).map((suggestion, index) => (
                                <button
                                    key={index}
                                    className="btn btn-small btn-suggestion"
                                    onClick={() => {
                                        const chartViz = VisualizationEngine.generateChart(
                                            suggestion.type,
                                            previewData,
                                            { title: `${suggestion.type} Chart` }
                                        );
                                        setVisualizations(prev => [...prev, {
                                            ...chartViz,
                                            name: `${suggestion.type} Chart`,
                                            type: 'chart'
                                        }]);
                                    }}
                                    title={suggestion.reason}
                                >
                                    📊 {suggestion.type}
                                </button>
                            ))}
                        </div>
                    )}
                </div>
            </div>

            {error && (
                <div className="error-banner">
                    <span className="error-icon">⚠️</span>
                    {error}
                    <button
                        className="error-close"
                        onClick={() => setError(null)}
                    >
                        ×
                    </button>
                </div>
            )}

            <div className="visualization-workspace">
                {/* Visualization Tabs */}
                {visualizations.length > 0 && (
                    <div className="visualization-tabs">
                        {visualizations.map(viz => (
                            <div
                                key={viz.id}
                                className={`viz-tab ${activeVisualization?.id === viz.id ? 'active' : ''}`}
                                onClick={() => setActiveVisualization(viz)}
                            >
                                <span className="tab-name">{viz.name}</span>
                                <span className="tab-type">{viz.type}</span>
                                <button
                                    className="tab-close"
                                    onClick={(e) => {
                                        e.stopPropagation();
                                        handleDeleteVisualization(viz.id);
                                    }}
                                >
                                    ×
                                </button>
                            </div>
                        ))}
                    </div>
                )}

                {/* Visualization Content */}
                <div
                    className="visualization-container"
                    ref={visualizationContainerRef}
                >
                    {activeVisualization ? (
                        renderVisualizationContent(activeVisualization)
                    ) : (
                        <div className="no-visualization">
                            <div className="no-viz-icon">📊</div>
                            <h4>No Visualizations</h4>
                            <p>Create a custom visualization or use API response data to auto-generate charts and tables.</p>
                            <button
                                className="btn btn-primary"
                                onClick={() => setIsTemplateEditorOpen(true)}
                            >
                                Create Visualization
                            </button>
                        </div>
                    )}
                </div>
            </div>

            {/* Template Editor Modal */}
            {isTemplateEditorOpen && (
                <div className="template-editor-modal">
                    <div className="modal-overlay" onClick={() => setIsTemplateEditorOpen(false)} />
                    <div className="modal-content">
                        <div className="modal-header">
                            <h3>Create Custom Visualization</h3>
                            <button
                                className="modal-close"
                                onClick={() => setIsTemplateEditorOpen(false)}
                            >
                                ×
                            </button>
                        </div>

                        <div className="modal-body">
                            <div className="template-section">
                                <label>Use Prebuilt Template:</label>
                                <select
                                    value={selectedTemplate}
                                    onChange={(e) => handleTemplateSelect(e.target.value)}
                                    className="template-select"
                                >
                                    <option value="">Custom Template</option>
                                    {templateLibrary.map((template) => (
                                        <option key={template.id} value={template.id}>
                                            {template.name} - {template.description}
                                        </option>
                                    ))}
                                </select>
                            </div>

                            <div className="template-section">
                                <label>Template (Handlebars syntax):</label>
                                <textarea
                                    value={customTemplate}
                                    onChange={(e) => setCustomTemplate(e.target.value)}
                                    placeholder="Enter your Handlebars template here..."
                                    className="template-textarea"
                                    rows={10}
                                />
                            </div>

                            <div className="template-section">
                                <label>Available Data:</label>
                                <pre className="data-preview">
                                    {JSON.stringify(previewData, null, 2)}
                                </pre>
                            </div>
                        </div>

                        <div className="modal-footer">
                            <button
                                className="btn btn-secondary"
                                onClick={() => setIsTemplateEditorOpen(false)}
                            >
                                Cancel
                            </button>
                            <button
                                className="btn btn-primary"
                                onClick={handleCustomVisualization}
                            >
                                Create Visualization
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default VisualizationTab;
