import React, { useState, useEffect, useRef, useCallback, useMemo, useId } from 'react';
import { FiPlus, FiRefreshCw, FiBarChart2, FiX, FiAlertTriangle } from 'react-icons/fi';
import { VisualizationEngine } from '../services/VisualizationEngine';
import TemplateLibraryManager from '../services/TemplateLibraryManager';
import ChartRenderer from './ChartRenderer';
import NetworkFlowRenderer from './NetworkFlowRenderer';
import TemplateEditorModal from './TemplateEditorModal';
import '../../Protocols/tester-shell.css';
import DOMPurify from 'dompurify';
import './VisualizationTab.css';
import './VisualizationTabContent.css';

const SANITIZE_CONFIG = { FORBID_ATTR: ['style'], FORBID_TAGS: ['style'] };

const sanitizeHtml = (html) => DOMPurify.sanitize(html, SANITIZE_CONFIG);

const NOOP = () => {};

const VisualizationTab = ({
    apiResponse = null,
    nodes = [],
    onVisualizationUpdate = NOOP,
    visualizationContext = null
}) => {
    const panelId = useId();
    const [visualizations, setVisualizations] = useState([]);
    const [activeVisualization, setActiveVisualization] = useState(null);
    const [customTemplate, setCustomTemplate] = useState('');
    const [selectedTemplate, setSelectedTemplate] = useState('');
    const [isTemplateEditorOpen, setIsTemplateEditorOpen] = useState(false);
    const [error, setError] = useState(null);
    const [templateLibrary, setTemplateLibrary] = useState([]);
    const [suggestedCharts, setSuggestedCharts] = useState([]);
    const tabRefs = useRef([]);

    // Notify parent whenever visualizations change
    useEffect(() => {
        onVisualizationUpdate(visualizations);
    }, [visualizations, onVisualizationUpdate]);

    // Keep active visualization in sync if it was deleted
    useEffect(() => {
        if (activeVisualization && !visualizations.some(v => v.id === activeVisualization.id)) {
            setActiveVisualization(visualizations[0] || null);
        }
    }, [visualizations, activeVisualization]);

    // Sample data for testing when no API response is available
    const sampleData = useMemo(() => ({
        users: [
            { name: 'John Doe', email: 'john@example.com', age: 30, status: 'active', score: 85 },
            { name: 'Jane Smith', email: 'jane@example.com', age: 25, status: 'active', score: 92 },
            { name: 'Bob Johnson', email: 'bob@example.com', age: 35, status: 'inactive', score: 78 },
            { name: 'Alice Brown', email: 'alice@example.com', age: 28, status: 'active', score: 95 },
            { name: 'Charlie Wilson', email: 'charlie@example.com', age: 42, status: 'pending', score: 88 }
        ],
        analytics: {
            pageViews: 15420,
            uniqueVisitors: 8750,
            bounceRate: 34.2,
            avgSessionDuration: 245,
            conversionRate: 3.8
        },
        performance: {
            responseTime: 245,
            errorRate: 1.2,
            uptime: 99.8,
            throughput: 1540
        },
        status: 200,
        responseTime: 245,
        size: 2048,
        timestamp: new Date().toISOString()
    }), []);

    const previewData = useMemo(() => {
        if (visualizationContext && visualizationContext.responseData) {
            return visualizationContext.responseData.data || visualizationContext.responseData;
        }
        if (apiResponse) return apiResponse;
        return sampleData;
    }, [visualizationContext, apiResponse, sampleData]);

    const loadTemplateLibrary = useCallback(() => {
        const templates = TemplateLibraryManager.getAllTemplates();
        setTemplateLibrary(templates);
    }, []);

    const generateChartSuggestions = useCallback((data) => {
        const suggestions = VisualizationEngine.suggestChartTypes(data);
        setSuggestedCharts(suggestions);
    }, []);

    const generateDefaultVisualizations = useCallback((data) => {
        try {
            const newVisualizations = [];

            // Auto-generate visualizations using the enhanced engine
            const autoGenerated = VisualizationEngine.generateFromResponse(data, {
                maxRows: 50,
                title: 'API Response Data'
            });

            newVisualizations.push(...autoGenerated);

            // If data has users array, create additional visualizations
            if (data.users && Array.isArray(data.users)) {
                // Age distribution chart
                const ageData = data.users.map(user => ({
                    label: user.name,
                    value: user.age
                }));

                const ageChart = VisualizationEngine.generateChart('bar', ageData, {
                    title: 'User Age Distribution',
                    xLabel: 'Users',
                    yLabel: 'Age'
                });

                newVisualizations.push({
                    ...ageChart,
                    name: 'Age Distribution',
                    type: 'chart'
                });

                // Status pie chart if score exists
                if (data.users[0].score) {
                    const scoreData = data.users.map(user => ({
                        label: user.name,
                        value: user.score
                    }));

                    const scoreChart = VisualizationEngine.generateChart('line', scoreData, {
                        title: 'User Scores',
                        xLabel: 'Users',
                        yLabel: 'Score'
                    });

                    newVisualizations.push({
                        ...scoreChart,
                        name: 'User Scores Trend',
                        type: 'chart'
                    });
                }
            }

            // Analytics data visualization
            if (data.analytics) {
                const analyticsChart = VisualizationEngine.generateChart('doughnut', data.analytics, {
                    title: 'Analytics Overview'
                });

                newVisualizations.push({
                    ...analyticsChart,
                    name: 'Analytics Doughnut',
                    type: 'chart'
                });
            }

            // Performance metrics
            if (data.performance) {
                const performanceMetrics = VisualizationEngine.createMetrics(data.performance, {
                    title: 'Performance Metrics'
                });

                newVisualizations.push({
                    ...performanceMetrics,
                    name: 'Performance Dashboard',
                    type: 'metrics'
                });
            }

            setVisualizations(newVisualizations);

            // Set first visualization as active
            if (newVisualizations.length > 0) {
                setActiveVisualization(newVisualizations[0]);
            }

        } catch (err) {
            setError(`Failed to generate visualizations: ${err.message}`);
            // Clear stale generated visualizations on failure
            setVisualizations([]);
            setActiveVisualization(null);
        }
    }, []);

    // Load template library once on mount
    useEffect(() => {
        loadTemplateLibrary();
    }, [loadTemplateLibrary]);

    // Regenerate when previewData changes
    useEffect(() => {
        if (!previewData) return;
        generateDefaultVisualizations(previewData);
        generateChartSuggestions(previewData);
    }, [previewData, generateDefaultVisualizations, generateChartSuggestions]);

    const handleTemplateSelect = (templateId) => {
        setSelectedTemplate(templateId);
        const template = TemplateLibraryManager.getTemplate(templateId);
        if (template) {
            setCustomTemplate(template.template);
        }
    };

    const handleCustomVisualization = () => {
        try {
            if (!customTemplate.trim()) {
                setError('Please enter a template');
                return;
            }

            setError(null);
            const customViz = VisualizationEngine.set(customTemplate, previewData);

            const newVisualization = {
                ...customViz,
                name: 'Custom Visualization',
                type: 'custom',
                rendered: sanitizeHtml(customViz.rendered)
            };

            setVisualizations(prev => [...prev, newVisualization]);
            setActiveVisualization(newVisualization);
            setIsTemplateEditorOpen(false);
        } catch (err) {
            setError(`Template error: ${err.message}`);
        }
    };

    const handleDeleteVisualization = (vizId) => {
        setVisualizations(prev => {
            tabRefs.current = tabRefs.current.slice(0, prev.length - 1);
            return prev.filter(viz => viz.id !== vizId);
        });
        VisualizationEngine.remove(vizId);
    };

    const handleTabKeyDown = (e, index) => {
        if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            setActiveVisualization(visualizations[index]);
            return;
        }

        let nextIndex = index;
        if (e.key === 'ArrowRight') {
            nextIndex = (index + 1) % visualizations.length;
        } else if (e.key === 'ArrowLeft') {
            nextIndex = (index - 1 + visualizations.length) % visualizations.length;
        } else if (e.key === 'Home') {
            nextIndex = 0;
        } else if (e.key === 'End') {
            nextIndex = visualizations.length - 1;
        } else {
            return;
        }

        e.preventDefault();
        tabRefs.current[nextIndex]?.focus();
        setActiveVisualization(visualizations[nextIndex]);
    };

    const renderVisualizationContent = (visualization) => {
        if (!visualization) return null;

        // If it's a chart visualization, render using ChartRenderer
        if (visualization.type === 'chart' && visualization.data && visualization.data.chartConfig) {
            const chartConfig = visualization.data.chartConfig;
            return (
                <div className="ts-panel visualization-card">
                    <ChartRenderer
                        type={chartConfig.type}
                        data={chartConfig.data}
                        options={chartConfig.options}
                    />
                </div>
            );
        }

        const safeHtml = sanitizeHtml(visualization.rendered);

        // If it's a network flow visualization, render using NetworkFlowRenderer
        if (visualization.type === 'network' && visualization.data) {
            return (
                <div className="ts-panel visualization-card">
                    <NetworkFlowRenderer
                        data={visualization.data}
                        options={visualization.options}
                    />
                </div>
            );
        }

        return (
            <div
                className="ts-panel visualization-card visualization-content"
                dangerouslySetInnerHTML={{ __html: safeHtml }}
            />
        );
    };

    return (
        <div className="visualization-tab">
            <div className="visualization-header">
                <div className="header-left">
                    <div className="ts-eyebrow">Data Visualizations</div>
                    <span className="ts-badge">{visualizations.length}</span>
                </div>
                <div className="header-actions">
                    <button
                        className="ts-btn primary"
                        onClick={() => setIsTemplateEditorOpen(true)}
                    >
                        <FiPlus size={14} /> Create Custom
                    </button>
                    <button
                        className="ts-btn"
                        onClick={() => generateDefaultVisualizations(previewData)}
                    >
                        <FiRefreshCw size={14} /> Refresh
                    </button>
                    {suggestedCharts.length > 0 && (
                        <div className="chart-suggestions">
                            <span className="ts-muted">Suggested:</span>
                            {suggestedCharts.slice(0, 3).map((suggestion) => (
                                <button
                                    key={suggestion.type}
                                    className="ts-btn ts-btn-suggestion"
                                    onClick={() => {
                                        const chartViz = VisualizationEngine.generateChart(
                                            suggestion.type,
                                            previewData,
                                            { title: `${suggestion.type} Chart` }
                                        );
                                        setVisualizations(prev => [...prev, {
                                            ...chartViz,
                                            name: `${suggestion.type} Chart`,
                                            type: 'chart'
                                        }]);
                                    }}
                                    title={suggestion.reason}
                                >
                                    <FiBarChart2 size={14} /> {suggestion.type}
                                </button>
                            ))}
                        </div>
                    )}
                </div>
            </div>

            {error && (
                <div className="error-banner" role="alert">
                    <FiAlertTriangle size={16} />
                    <span className="error-message">{error}</span>
                    <button
                        className="error-close"
                        onClick={() => setError(null)}
                        aria-label="Dismiss error"
                    >
                        <FiX size={14} />
                    </button>
                </div>
            )}

            <div className="visualization-workspace">
                {/* Visualization Tabs */}
                {visualizations.length > 0 && (
                    <div className="visualization-tabs" role="tablist">
                        {visualizations.map((viz, index) => (
                            <div
                                key={viz.id}
                                ref={(el) => (tabRefs.current[index] = el)}
                                className={`viz-tab ${activeVisualization?.id === viz.id ? 'active' : ''}`}
                            >
                                <button
                                    type="button"
                                    className="viz-tab-trigger"
                                    onClick={() => setActiveVisualization(viz)}
                                    role="tab"
                                    aria-selected={activeVisualization?.id === viz.id}
                                    aria-controls={panelId}
                                    id={`${panelId}-tab-${viz.id}`}
                                    tabIndex={activeVisualization?.id === viz.id ? 0 : -1}
                                    onKeyDown={(e) => handleTabKeyDown(e, index)}
                                >
                                    <span className="tab-name">{viz.name}</span>
                                    <span className="ts-badge">{viz.type}</span>
                                </button>
                                <button
                                    type="button"
                                    className="tab-close"
                                    onClick={() => handleDeleteVisualization(viz.id)}
                                    aria-label={`Close ${viz.name}`}
                                    tabIndex={-1}
                                >
                                    <FiX size={12} />
                                </button>
                            </div>
                        ))}
                    </div>
                )}

                {/* Visualization Content */}
                <div
                    id={panelId}
                    className="visualization-container ts-inset"
                    role="tabpanel"
                    aria-labelledby={activeVisualization ? `${panelId}-tab-${activeVisualization.id}` : undefined}
                >
                    {activeVisualization ? (
                        renderVisualizationContent(activeVisualization)
                    ) : (
                        <div className="no-visualization">
                            <div className="no-viz-icon" aria-hidden="true">📊</div>
                            <h4>No Visualizations</h4>
                            <p>Create a custom visualization or use API response data to auto-generate charts and tables.</p>
                            <button
                                className="ts-btn primary"
                                onClick={() => setIsTemplateEditorOpen(true)}
                            >
                                <FiPlus size={14} /> Create Visualization
                            </button>
                        </div>
                    )}
                </div>
            </div>

            {/* Template Editor Modal */}
            {isTemplateEditorOpen && (
                <TemplateEditorModal
                    selectedTemplate={selectedTemplate}
                    templateLibrary={templateLibrary}
                    customTemplate={customTemplate}
                    previewData={previewData}
                    onClose={() => setIsTemplateEditorOpen(false)}
                    onSelectTemplate={handleTemplateSelect}
                    onTemplateChange={setCustomTemplate}
                    onCreate={handleCustomVisualization}
                />
            )}
        </div>
    );
};

export default VisualizationTab;
